---
# general settings
# default_username: us3r
dot_forward_email: torworx+dev@gmail.com
private_key: .ssh/id_rsa
public_key: .ssh/id_rsa.pub
ntpserver: pool.ntp.org
timezone: Asia/Shanghai

# default sshd port
sshd_port: 22

# generate random passwords for default user and root user
# default_password: "{{lookup('password', '/dev/null length=15 chars=ascii_letters,digits')}}"
# root_password: "{{lookup('password', '/dev/null length=15 chars=ascii_letters,digits')}}"

# unattended packages install configuration
unattended_mail: "{{dot_forward_email}}"
unattended_remove_unused_dependencies: true
unattended_automatic_reboot_time: "03:00"
unattended_update_days: "Sat"
unattended_clean_interval: 7

# fail2ban
fail2ban_loglevel: INFO
fail2ban_services:
  - name: ssh
    port: ssh
    filter: sshd
    logpath: /var/log/auth.log
