---
# flag to install or skip docker module installation and configuration
install_docker: true

#
# docker
# https://github.com/nickjj/ansible-docker
#
docker__channel: ["stable"]
# When set to "", the current latest version of Docker will be installed
docker__version: ""
# When set to a specific version, that version of Docker will be installed and pinned
# For example, pin it to 24.0.
# docker__version: "24.0"
# For example, pin it to a more precise version of 24.0.
# docker__version: "24.0.6"

docker__state: "present"

# When set to "", the current latest version of Docker Compose v2 will be installed
docker__compose_v2_version: ""
# When set to a specific version, that version of Docker Compose v2 will be installed and pinned
# For example, pin it to 2.21.
# docker__compose_v2_version: "2.21"
# For example, pin it to a more precise version of 2.21.
# docker__compose_v2_version: "2.21.0"

docker__users: ["{{default_username}}"]
docker__daemon_flags:
  - "-H unix://"
  #- "-H unix:// --iptables=false"
# "a" removes unused images (useful in production).
# "f" forces it to happen without prompting you to agree.
docker__cron_jobs_prune_flags: "af"
docker__cron_jobs:
  - name: "Docker disk clean up"
    job: "docker system prune -{{docker__cron_jobs_prune_flags}} > /dev/null 2>&1"
    schedule: ["0", "0", "*", "*", "0"]
    cron_file: "docker-disk-clean-up"
    user: "{{(docker__users | first) | d('root')}}"
    state: "present"
