---
- name: Configure /etc/network/interfaces
  ansible.builtin.template:
    src: "{{ interfaces_template }}"
    dest: /etc/network/interfaces
    mode: "0600"
  register: _configure_interfaces

- name: Reboot the machine
  ansible.builtin.reboot:
