---
- name: Run Linux Setup
  hosts: prod
  vars_files:
    - .default.yml
    - group_vars/all.yml
    - group_vars/keys.yml
    - group_vars/apt.yml
    - group_vars/docker.yml
    - group_vars/monit.yml
    - group_vars/networking.yml
    - group_vars/vault.yml
  user: "{{default_username}}"  # run whole script with default user
  become: true
  roles:  # order is not random!
    - role: nickjj.fail2ban
      tags: fail2ban
    - role: common
      tags: common
    # - role: exim4
    #   tags: common
    - role: viasite-ansible.zsh
      tags: common
      zsh_user: "{{default_username}}"
    - role: nodejs
      tags: nodejs
    # - role: ufw
    #   tags: ufw
    - role: user
      tags: user
    - role: ssh
      tags: ssh
    - role: nickjj.docker
      when: install_docker == true
      tags: docker
    - role: docker
      when: install_docker == true
      tags: docker
    # - role: jnv.debian-backports
    #   tags: common
    # - role: ansible-monit
    #   tags: common
    - role: hifis.unattended_upgrades
      tags: common
    - role: sysctl
      tags: sysctl
    - role: networking
      tags: networking
    - role: reboot
      tags: reboot
