---
# - name: Update default user, belonging to sudo group
#   ansible.builtin.user:
#     name: "{{ default_username }}"
#     groups: sudo
#     create_home: true
#     shell: /bin/bash
#     generate_ssh_key: true
#     ssh_key_bits: 2048
#     ssh_key_file: .ssh/id_rsa
#     state: present

# - name: Update user password if default_password is defined
#   ansible.builtin.user:
#     name: "{{ default_username }}"
#     password: "{{ default_password | password_hash('sha512') }}"
#     update_password: always
#   when: default_password is defined

# - name: Set ansible_sudo_pass if default_password is defined
#   ansible.builtin.set_fact:
#     ansible_sudo_pass: "{{ default_password }}"
#   when: default_password is defined

- name: Ensure sudo group has sudo privileges without password
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%sudo"
    line: "%sudo ALL=(ALL) NOPASSWD:ALL"
    validate: "/usr/sbin/visudo -cf %s"

# copy local files to remote
- name: Install .forward file in users' folders
  ansible.builtin.template:
    src: dot.forward.j2
    dest: "{{ item }}/.forward"
    owner: "{{ default_username }}"
    group: "{{ default_username }}"
    mode: "0600"
  with_items:
    - /root
    - /home/{{ default_username }}

- name: Clone dotfiles repository
  become: true
  become_user: "{{ item.user }}"
  ansible.builtin.git:
    repo: "https://github.com/olivomarco/dotfiles.git"
    version: master
    dest: "{{item.path}}"
    accept_hostkey: true
    clone: true
    update: true
  with_items:
    - { user: "{{default_username}}", path: "/home/{{default_username}}/dotfiles" }
    - { user: "root", path: "/root/dotfiles" }

# - name: Run dotfiles/setup/setup-user.sh for {{item.user}}
#   become_user: "{{item.user}}"
#   shell: "{{item.path}}/setup/setup-user.sh"
#   with_items:
#     - {user: "{{default_username}}", path: "/home/{{default_username}}/dotfiles"}
#     - {user: "root", path: "/root/dotfiles"}

- name: Change owner of dotfiles in {{default_username}} folder
  ansible.builtin.file:
    path: "/home/{{default_username}}/dotfiles"
    owner: "{{default_username}}"
    group: "{{default_username}}"
    recurse: true

- name: Setup authorized keys from github
  ansible.posix.authorized_key:
    user: "{{ default_username }}"
    state: present
    key: "https://github.com/{{ item }}.keys"
  with_items: "{{ github_users }}"
  when: github_users is defined

- name: Setup authorized keys from local for {{default_username}}
  ansible.posix.authorized_key:
    user: "{{default_username}}"
    state: present
    key: "{{ lookup('file', item) }}"
  with_fileglob:
    - "{{ lookup('env','HOME') + '/.ssh/id_*.pub' }}"
  when: setup_authorized_keys_from_local == true

- name: Setup authorized keys from local for root
  ansible.posix.authorized_key:
    user: "root"
    state: present
    key: "{{ lookup('file', item) }}"
  with_fileglob:
    - "{{ lookup('env','HOME') + '/.ssh/id_*.pub' }}"
  when: setup_authorized_keys_from_local == true  

# - name: Change root password
#   ansible.builtin.user:
#     name: root
#     password: "{{ root_password | password_hash('sha512') }}"
#     update_password: always
#   when: root_password is defined

- name: Run chsh to /usr/bin/zsh for default user and root
  ansible.builtin.user:
    name: "{{item}}"
    shell: /usr/bin/zsh
  with_items:
    - "{{default_username}}"
    - "root"

- name: Show default user password
  ansible.builtin.debug:
    msg: "user '{{ default_username }}' generated password: {{ default_password }}"
  when: default_password is defined

- name: Show root password
  ansible.builtin.debug:
    msg: "user 'root' generated password: {{ root_password }}"
  when: root_password is defined
