---
- name: Set up exim4 conf
  ansible.builtin.template:
    src: update-exim4.conf.conf.j2
    dest: /etc/exim4/update-exim4.conf.conf
    owner: root
    group: root
    mode: "0644"

- name: Set up exim4 password file
  ansible.builtin.template:
    src: passwd.client.j2
    dest: /etc/exim4/passwd.client
    owner: root
    group: Debian-exim
    mode: "0640"

- name: Set up exim4 localmacros
  ansible.builtin.template:
    src: exim4.conf.localmacros.j2
    dest: /etc/exim4/exim4.conf.localmacros
    owner: root
    group: root
    mode: "0644"
  notify: Restart exim4
