---
- name: Apply custom connection ufw rules
  community.general.ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
    src: "{{ item.src }}"
    proto: "{{ item.proto }}"
    direction: "{{ item.direction }}"
  with_items: "{{ ufw_rules }}"

- name: Enable firewall
  community.general.ufw:
    state: enabled
    default: deny
    logging: true
  notify: reload ufw
