---
- name: Restart ntp
  ansible.builtin.service:
    name: ntp
    state: restarted

- name: Restart cron
  ansible.builtin.service:
    name: cron
    state: restarted

- name: Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted

- name: Restart exim4
  ansible.builtin.service:
    name: exim4
    state: restarted
