---
- name: Upgrade packages
  ansible.builtin.apt:
    upgrade: full

- name: Install packages
  ansible.builtin.apt:
    name: "{{ packages_to_install }}"
    state: present
    update_cache: true
    allow_unauthenticated: true

- name: Install mozilla/sops
  ansible.builtin.get_url:
    url: https://github.com/mozilla/sops/releases/download/v3.5.0/sops-v3.5.0.linux
    dest: /usr/bin/sops
    mode: "0755"
    owner: root
    group: root

# - name: Enable dm_crypt module
#   modprobe:
#     name: dm_crypt
#     state: present

- name: Enable compress on logrotate
  ansible.builtin.lineinfile:
    dest: /etc/logrotate.conf
    regexp: ^#?compress
    line: compress
    state: present

# - name: Send logcheck results to right email address
#   lineinfile:
#     dest: /etc/logcheck/logcheck.conf
#     regexp: "^#?SENDMAILTO="
#     line: "SENDMAILTO=\"{{dot_forward_email}}\""
#     state: present

# - name: Copy local logcheck ignore rules
#   copy:
#     src: templates/local-rules
#     dest: /etc/logcheck/ignore.d.server/local-rules
#     owner: root
#     group: logcheck
#     mode: u=rw,g=r,o=r

- name: Configure timezone
  community.general.timezone:
    name: "{{ timezone }}"

- name: Configure ntp client and restart it
  ansible.builtin.template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    mode: "0600"
  notify:
    - Restart ntp
    - Restart cron

- name: Make fail2ban work with ufw
  ansible.builtin.lineinfile:
    dest: "{{ item }}"
    regexp: ^banaction
    line: banaction = ufw
    state: present
  with_items:
    - /etc/fail2ban/jail.conf
    - /etc/fail2ban/jail.local
  notify:
    - Restart fail2ban
