---
- name: Ensure group "docker" exists
  ansible.builtin.group:
    name: docker
    state: present

- name: Ensure default user belongs also to docker group
  ansible.builtin.user:
    name: "{{ default_username }}"
    groups: docker
    append: true

- name: Add rsyslog custom rules for Docker
  ansible.builtin.copy:
    src: templates/docker.conf
    dest: /etc/rsyslog.d/docker.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Add logrotate custom rules for Docker logs
  ansible.builtin.copy:
    src: templates/logrotate_docker
    dest: /etc/logrotate.d/docker
    owner: root
    group: root
    mode: u=rw,g=r,o=r
